// <auto-generated />
using System;
using Billing52Group.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Billing52Group.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201021184634_ContractColumnType")]
    partial class ContractColumnType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Billing52Group.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<int?>("ContractGroupId")
                        .HasColumnName("contractgroupid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date1")
                        .HasColumnName("date1")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Date2")
                        .HasColumnName("date2")
                        .HasColumnType("date");

                    b.Property<int>("Fc")
                        .HasColumnName("fc")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.HasIndex("ContractGroupId")
                        .HasName("FKgroup1_idx");

                    b.ToTable("contract");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractAccount", b =>
                {
                    b.Property<int>("Yy")
                        .HasColumnName("yy")
                        .HasColumnType("int");

                    b.Property<bool>("Mm")
                        .HasColumnName("mm")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<double>("Summa")
                        .HasColumnName("summa")
                        .HasColumnType("double");

                    b.HasKey("Yy", "Mm", "ContractId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

                    b.HasIndex("ContractId")
                        .HasName("FKcontract7_idx");

                    b.ToTable("contractaccount");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractBalance", b =>
                {
                    b.Property<int>("Yy")
                        .HasColumnName("yy")
                        .HasColumnType("int");

                    b.Property<bool>("Mm")
                        .HasColumnName("mm")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<double>("Summa")
                        .HasColumnName("summa")
                        .HasColumnType("double");

                    b.HasKey("Yy", "Mm", "ContractId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

                    b.HasIndex("ContractId")
                        .HasName("FKcontract3_idx");

                    b.ToTable("contractbalance");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date")
                        .HasColumnType("date");

                    b.Property<double>("Summa")
                        .HasColumnName("summa")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasName("FKcontract2_idx");

                    b.ToTable("contractcharge");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.ToTable("contractgroup");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractLimit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<int>("Limitid")
                        .HasColumnName("limitid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startdate")
                        .HasColumnName("startdate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasName("FKcontract9_idx");

                    b.HasIndex("Limitid")
                        .HasName("FKlimit1_idx");

                    b.ToTable("contractlimit");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractModule", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<int>("Moduleid")
                        .HasColumnName("moduleid")
                        .HasColumnType("int");

                    b.HasKey("ContractId", "Moduleid")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex("Moduleid")
                        .HasName("FKmodule1_idx");

                    b.ToTable("contractmodule");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractParams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractId")
                        .HasColumnType("int");

                    b.Property<int>("ParamId")
                        .HasColumnName("paramId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasColumnType("varchar(125)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasName("FKcontract10_idx");

                    b.HasIndex("ParamId")
                        .HasName("FKparams1_idx");

                    b.ToTable("contractparams");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnName("paymentid")
                        .HasColumnType("int");

                    b.Property<double>("Summa")
                        .HasColumnName("summa")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasName("FKcontract4_idx");

                    b.HasIndex("PaymentId")
                        .HasName("FKpayment1_idx");

                    b.ToTable("contractpayment");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date1")
                        .HasColumnName("date1")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Date2")
                        .HasColumnName("date2")
                        .HasColumnType("date");

                    b.Property<int>("ServiceId")
                        .HasColumnName("serviceid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasName("FKcontract6_idx");

                    b.HasIndex("ServiceId")
                        .HasName("FKservice1_idx");

                    b.ToTable("contractservice");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startdate")
                        .HasColumnName("startdate")
                        .HasColumnType("date");

                    b.Property<int>("StatusId")
                        .HasColumnName("statusid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasName("FKcontract8_idx");

                    b.HasIndex("StatusId")
                        .HasName("FKstatus1_idx");

                    b.ToTable("contractstatus");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<int>("ContractId")
                        .HasColumnName("contractid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date1")
                        .HasColumnName("date1")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Date2")
                        .HasColumnName("date2")
                        .HasColumnType("date");

                    b.Property<int>("TariffPlanId")
                        .HasColumnName("tariffplanid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasName("FKcontract5_idx");

                    b.HasIndex("TariffPlanId")
                        .HasName("FKtariff1_idx");

                    b.ToTable("contracttariff");
                });

            modelBuilder.Entity("Billing52Group.Models.Limit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Limit1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("limit")
                        .HasColumnType("varchar(45)")
                        .HasDefaultValueSql("'0'")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.ToTable("limit");
                });

            modelBuilder.Entity("Billing52Group.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.ToTable("module");
                });

            modelBuilder.Entity("Billing52Group.Models.Parameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.ToTable("parameters");
                });

            modelBuilder.Entity("Billing52Group.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnName("date")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("Billing52Group.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<double>("Cost")
                        .HasColumnName("cost")
                        .HasColumnType("double");

                    b.Property<int>("Moduleid")
                        .HasColumnName("moduleid")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.HasIndex("Moduleid")
                        .HasName("FKmodule3_idx");

                    b.ToTable("service");
                });

            modelBuilder.Entity("Billing52Group.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.ToTable("status");
                });

            modelBuilder.Entity("Billing52Group.Models.TariffGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.ToTable("tariffgroup");
                });

            modelBuilder.Entity("Billing52Group.Models.TariffPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<double?>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cost")
                        .HasColumnType("double")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("TariffGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tariffgroupid")
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "latin1")
                        .HasAnnotation("MySql:Collation", "latin1_swedish_ci");

                    b.HasKey("Id");

                    b.HasIndex("TariffGroupId")
                        .HasName("FKmodule1_idx");

                    b.ToTable("tariffplan");
                });

            modelBuilder.Entity("Billing52Group.Models.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<bool>("Admin")
                        .HasColumnName("admin")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Login", "Password")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Billing52Group.Models.Contract", b =>
                {
                    b.HasOne("Billing52Group.Models.ContractGroup", "ContractGroup")
                        .WithMany("Contract")
                        .HasForeignKey("ContractGroupId")
                        .HasConstraintName("FKgroup1");
                });

            modelBuilder.Entity("Billing52Group.Models.ContractAccount", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractAccounts")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract7")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractBalance", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractBalance")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract3")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractCharge", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractCharge")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract2")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractLimit", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractLimit")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract9")
                        .IsRequired();

                    b.HasOne("Billing52Group.Models.Limit", "Limit")
                        .WithMany("ContractLimit")
                        .HasForeignKey("Limitid")
                        .HasConstraintName("FKlimit1")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractModule", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractModule")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract1")
                        .IsRequired();

                    b.HasOne("Billing52Group.Models.Module", "Module")
                        .WithMany("ContractModule")
                        .HasForeignKey("Moduleid")
                        .HasConstraintName("FKmodule2")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractParams", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractParams")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract10")
                        .IsRequired();

                    b.HasOne("Billing52Group.Models.Parameters", "Param")
                        .WithMany("ContractParams")
                        .HasForeignKey("ParamId")
                        .HasConstraintName("FKparams1")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractPayment", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractPayment")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract4")
                        .IsRequired();

                    b.HasOne("Billing52Group.Models.Payment", "Payment")
                        .WithMany("ContractPayment")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FKpayment1")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractService", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractService")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract6")
                        .IsRequired();

                    b.HasOne("Billing52Group.Models.Service", "Service")
                        .WithMany("ContractService")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FKservice1")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractStatus", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractStatus")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract8")
                        .IsRequired();

                    b.HasOne("Billing52Group.Models.Status", "Status")
                        .WithMany("ContractStatus")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FKstatus1")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.ContractTariff", b =>
                {
                    b.HasOne("Billing52Group.Models.Contract", "Contract")
                        .WithMany("ContractTariff")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FKcontract5")
                        .IsRequired();

                    b.HasOne("Billing52Group.Models.TariffPlan", "TariffPlan")
                        .WithMany("ContractTariff")
                        .HasForeignKey("TariffPlanId")
                        .HasConstraintName("FKtariff1")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.Service", b =>
                {
                    b.HasOne("Billing52Group.Models.Module", "Module")
                        .WithMany("Service")
                        .HasForeignKey("Moduleid")
                        .HasConstraintName("FKmodule3")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing52Group.Models.TariffPlan", b =>
                {
                    b.HasOne("Billing52Group.Models.TariffGroup", "TariffGroup")
                        .WithMany("TariffPlan")
                        .HasForeignKey("TariffGroupId")
                        .HasConstraintName("FKmodule1");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
